# For more info on HTTP files go to https://aka.ms/vs/httpfile
@prefix=http
@hostname=http://localhost
@port=7014
@baseUrl={{hostname}}:{{port}}

###
POST {{baseUrl}}/api/HydraluxEnquiryStart
content-type: application/json
{
  "Name": "Richard Jones",
  "Phone":"9999 999 999",
  "Email":"rjjones79@hotmail.com",
  "ServiceRequired":"Driveway Clean",
  "Message": "This a test message."
}



